In [4]:
import gym

env = gym.make('Reacher-v2')


In [5]:
print(env.observation_space.shape, env.action_space.shape)

(11,) (2,)


In [27]:
obs = env.reset()
print(obs)
print(env.sim.data.qpos)
print(env.sim.data.qvel)

[ 0.99851491  0.99994071  0.05447909 -0.01088972 -0.0978359  -0.13780612
  0.00244727  0.00189328  0.30758278  0.14805028  0.        ]
[ 0.05450607 -0.01088994 -0.0978359  -0.13780612]
[0.00244727 0.00189328 0.         0.        ]


In [28]:
st = env.sim.get_state()
print(st)
print(env.sim.data.qpos)
print(env.sim.data.qvel)

MjSimState(time=0.0, qpos=array([ 0.05450607, -0.01088994, -0.0978359 , -0.13780612]), qvel=array([0.00244727, 0.00189328, 0.        , 0.        ]), act=None, udd_state={})
[ 0.05450607 -0.01088994 -0.0978359  -0.13780612]
[0.00244727 0.00189328 0.         0.        ]


In [29]:
obs = env.reset()
print(obs)
print(env.sim.data.qpos)
print(env.sim.data.qvel)

[ 9.98816012e-01  9.98525495e-01  4.86474573e-02 -5.42847717e-02
  5.68376166e-02 -1.31636684e-01 -1.72325536e-05  3.22611473e-03
  1.53042232e-01  1.35880505e-01  0.00000000e+00]
[ 0.04866667 -0.05431147  0.05683762 -0.13163668]
[-1.72325536e-05  3.22611473e-03  0.00000000e+00  0.00000000e+00]


In [30]:
env.sim.set_state(st)
print(env.sim.data.qpos)
print(env.sim.data.qvel)

[ 0.05450607 -0.01088994 -0.0978359  -0.13780612]
[0.00244727 0.00189328 0.         0.        ]


In [6]:
for i in range(6):
    env.reset()
    rew = 0
    
    while True:
        _, r, done, _ = env.step(env.action_space.sample())
        
        rew += r
        
        if done==True:
            print('Ep %d: %.2f' % (i+1, rew))
            
            break

Ep 1: -48.75
Ep 2: -44.70
Ep 3: -39.31
Ep 4: -45.03
Ep 5: -37.28
Ep 6: -40.89


In [1]:
import torch as T
import torch.nn as nn

In [2]:
state_size = 24
compare = 5
print((-compare*T.ones(state_size) == -compare*T.ones(state_size)))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=torch.uint8)
